{
 "title": "mqtt",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Raw Humidity",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"humidity\")"
    }
   ]
  },
  {
   "title": "ThermalArray Raw",
   "type": "logs",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"thermalArray\")"
    }
   ]
  },
  {
   "title": "Raw Thermal",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"temperature\")"
    }
   ]
  },
  {
   "title": "ThermalArray  Heat Map",
   "type": "marcuscalidus-svg-panel",
   "gridPos": { "h": 18, "w": 7, "x": 17, "y": 6 },
   "format": "short",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default_test1_sensors",
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"thermalArray\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"humidity\")"
    }
   ]
  },
  {
   "title": "temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"temperature\")"
    }
   ]
  },
  {
   "title": "humid",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"humidity\")"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"humidity\")"
    }
   ]
  },
  {
   "title": "Temp x Humid",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"humidity\" or r[\"unit\"] == \"temperature\")"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"temperature\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"unit\"] == \"temperature\")"
    }
   ]
  }
 ]
}