version: "3.9"
services:
  influxdb:
    image: influxdb:2.6.1-alpine
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - "8086:8086"
    volumes:
      - ./volume/influxdb:/var/lib/influxdb
    restart: always
  grafana:
    image: grafana/grafana:9.4.3
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - "4000:3000"
    volumes:
      - ./volume/grafana:/var/lib/grafana
    restart: always
