version: "3.9"
services:
  influxdb:
    image: influxdb:2.6.1-alpine
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminadmin
      DOCKER_INFLUXDB_INIT_ORG: admin
      DOCKER_INFLUXDB_INIT_BUCKET: mqtt
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: tokentoken
    ports:
      - "8086:8086"
    volumes:
      - ./volume/influxdb:/var/lib/influxdb
    restart: always
  grafana:
    image: grafana/grafana:9.4.3
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - "4000:3000"
    volumes:
      - ./volume/grafana:/var/lib/grafana
    restart: always
